version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: admin
      MYSQL_PASSWORD: pwd
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: local-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: pwd
      PMA_TITLE: "name"
    ports:
      - "9000:80"
    depends_on:
      - mysql
